[package]
name = "veyronis-diff"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Semantic behavioral diff and divergence analysis engine for Veyronis"

[dependencies]
veyronis-ir = { workspace = true }
veyronis-graph = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
colored = { workspace = true }
tabled = { workspace = true }
