[package]
name = "veyronis-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Continuous background ring-buffer supervisor and incident snapshot daemon for Veyronis"

[dependencies]
veyronis-core = { workspace = true }
veyronis-format = { workspace = true }
veyronis-detect = { workspace = true }
veyronis-ir = { workspace = true }
veyronis-collector-api = { workspace = true }
collector-windows = { workspace = true }
collector-linux = { workspace = true }
collector-macos = { workspace = true }
collector-portable = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
colored = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
